### ISSUE TITLE
Doesn't seem to work with Bullseye + RPi Zero2

### ISSUE THREAD

**Issue by Fredrum** [jc-kynesim/hello_drmprime#2]
Hello!
I recently got a RPi Zero 2 W and installed Bullseye on it and then the program I'm working on (Chiaki).
It wouldn't show me video so just now build and ran 'hello_drmprime' on it.  It doesn't work and I get the message,

Failed to find a V4L2 device for h265
and
Failed to get HW surface format

Maybe this is not that surprising because when I added 
dtoverlay=rpivid-v4l2
to my boot config I got an error message on startup saying this driver couldn't work with, (and then some code, the CPU?)
It was a dialog popup that disappeared too fast for me to remember what the ID/name was.

Have you tried this on the mentioned Pi board+Bullseye yet?
Do you know anything about what this might mean?

Cheers
Fred

**Comment by jc-kynesim** [comment]
If you look in the output from "dmesg" you may get the missing error message.
I'm not honestly certain exactly what capabilities the Zero 2 are but my guess would be its missing the h/w block for H265 decode.

**Comment by Fredrum** [comment]
I'll take a look now. It actually didn't work with a h264 jellyfish either.
I'll update here with the dmesg.

**Comment by jc-kynesim** [comment]
I'm informed that a Zero 2 should have H264 h/w decode, but not H265

**Comment by Fredrum** [comment]
I couldn't spot the error message I remember from the pop-up and instead it seems like its using the v4l2 driver. I see messages like,
```
bcm2835-dma 3f007000.dma: DMA legacy API manager, dmachans=0x1
...
Using Buffer DMA mode
...
mmc0: sdhost-bmc2835 loaded - DMA enabled (>1)
...
bcm2835_v4l2: module is from the staging directory, the quality is unknown, you hav been warned.
...
... /dev/video10 registered
... Loaded V4L2 decode
```

When I'm running hello on the h264 jellyfish I get this reply,
`decoder h264 does not support device type drm.`

but I can't recall maybe this was how it was before and I ended up tweaking something for h264 on the Pi4?
I'm going to load up the code I have on my other SD card and take a look.

UPDATE:  Yes I had added a few things maybe to run h264. I'm still getting some DRM fail messages but maybe I missed something else too.
(btw, I'm just using a Zero2 because I bricked my Pi4 and can't find any new ones)

**Comment by Fredrum** [comment]
Hm not sure yet...the message that gets repeated for each frame in the 'hello' main loop is,
`Frame (format=0) not DRM_PRiME`

It looks like the v4l2 light blue messages are ok.
I'll have to try to get more messages I think.

**Comment by jc-kynesim** [comment]
Yeah - hello_drmprime was only written to work with H265, but can be tweaked to deal with h264. The ffmpeg chooser will select the "h264" video decode, you need "h264_v4l2m2m".

**Comment by jc-kynesim** [comment]
For what its worth the version I've just pushed will now cope with H264 correctly (for a Pi - I'm not sure how this should auto-select correctly on other machines)

**Comment by Fredrum** [comment]
I just received my replacement RPi4b today and tested this with my Bullseye SD card and it works perfectly.
On my Zero 2W h264 also works nicely. So everything A-Ok sorry about the confusion not sure what I did.

Cheers!
